- name: Init linux
  hosts: 10.1.1.214
  tags: test
  become: yes
  tasks:
  - name: Install Docker Dependencies
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - docker.io
      - curl
      - net-tools
  - name: Create linux user
    user:
      name: devops
      shell: /bin/bash
      groups: sudo,docker
      create_home: yes
      append: yes
      state: present
