- name: Update repositories cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install a list of packages
  become: yes
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg

- name: Setup keyrings
  become: yes
  ansible.builtin.shell: install -m 0755 -d /etc/apt/keyrings
  

- name: Get docker gpg key and save to files
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/dockergpg

- name: De-Armor Docker GPG key
  become: yes
  ansible.builtin.shell:  gpg --dearmor < /tmp/dockergpg > /etc/apt/keyrings/docker.gpg


- name: Set permission
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r

- name: Add docker apt repo
  become: yes
  ansible.builtin.apt_repository: 
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    filename: docker.list
    state: present

- name: Install a list of packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add user to docker group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    uid: "{{ ansible_user_uid }}"
    group: docker