services:
  redis:
    image: redis:7-alpine
    container_name: redis-demo
  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://redis-demo:6379"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml"
  python-redis-client:
    image: python:3.10
    volumes:
      - "./main.py:/app/main.py"
      - "./flask.py:/app/flask.py"
      - "./entrypoint.sh:/app/entrypoint.sh"
    command: ["bash", "/app/entrypoint.sh"]
    tty: true
    stdin_open: true
    depends_on: ["redis"]