- name: create ec2 instance for test/demo
  hosts: localhost
  connection: local
  tasks:
    - name: create key pair using provided key_material
      amazon.aws.ec2_key:
        name: test-Sustain-Cloudwatch-Monitor-01
        key_material: '<import_public_key_string>'
        region: ap-southeast-1
        profile: <your_aws_profile>
        state: absent
    - name: create specific instance in specific subnet and using general default settings
      vars:
        subnet_id: <exists_subnet_id>
        ami_id: <exists_ami_id_in_the_region> # ubuntu-22.04 ap-southeast-1
      amazon.aws.ec2_instance:
        name: "test-Sustain-Cloudwatch-Monitor-01"
        profile: <your_aws_profile>
        key_name: "test-Sustain-Cloudwatch-Monitor-01"
        instance_type: t3.micro
        state: absent
        region: ap-southeast-1
        vpc_subnet_id: "{{ subnet_id }}"
        image_id: "{{ ami_id }}"
        volumes:
          - device_name: /dev/sda1 # only root disk
            ebs:
              delete_on_termination: true
              volume_size: 16
        tags:
          Name: cloudwatch_monitoring
          Env: test
          Group: Sustain
          Owner: demo