- name: include task_a and test loop in this task then the loop in task_a will what happend
  ansible.builtin.include_tasks: task_a.yml
  loop:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  loop_control:
    loop_var: outer_item